export const presentationConsts = {
  AuthEmailAndPasswordRequired: "Email and password are required",
  AuthEmailAlreadyRegistered: "Email already registered",
  AuthInvalidCredentials: "Invalid credentials",
  AuthAuthenticationFailed: "Authentication failed",
  AuthRegisterFailed: "Register failed",
  AuthGetUsersFailed: "Failed to retrieve users",
  AuthUserIdRequired: "User ID is required",
  AuthCreateUserFailed: "Failed to create user",
  AuthUpdateUserFailed: "Failed to update user",
  AuthDeleteUserFailed: "Failed to delete user",
  AuthUserNotFound: "User not found",

  // Library related constants
  LibraryBookNotFound: "Book not found",
  LibraryInvalidBookId: "Invalid book ID",
  LibraryBookDetailsRequired: "Book details are required",
  LibraryIsbnRequired: "ISBN is required",
  LibraryLabelRequired: "Label is required",
  LibraryBookAlreadyExists: "Book with this ISBN already exists",
  LibraryBookNotAvailable: "Book is not available for ordering",
  LibraryAuthorNameRequired: "Author first and last name are required",
  LibraryAuthorNotFound: "Author not found",
  LibraryPublisherNotFound: "Publisher not found",
  LibraryBookLiked: "Book liked successfully",
  LibraryUserIdRequired: "User ID is required",
  LibraryBookOrdered: "Book ordered successfully",
  LibraryBookReturned: "Book returned successfully",
  LibraryLabelRemoved: "Label removed from book successfully",
  LibraryLabelAdded: "Label added to book successfully",
  LibraryBookDeleted: "Book deleted successfully",
  LibraryBookSearchRequired: "Search query is required",
  LibraryBookSearchResults: "Search results for books",
  LibraryBookDetails: "Book details retrieved successfully",
  LibraryBookAdded: "Book added successfully",
  LibraryBookUpdated: "Book updated successfully",
  LibraryUserEmailRequired: "User email is required",
  LibraryInvalidAuthorId: "Invalid author ID",
  LibraryAuthorUpdated: "Author updated successfully",
  LibraryPublisherUpdated: "Publisher updated successfully",
  LibraryInvalidPublisherId: "Invalid publisher ID",
  LibraryReviewAddedSuccessfully: "Review added successfully",
  LibraryLikedOrDislikedSuccessfully: "Book liked or disliked successfully",
};
