export const domainConsts = {
    UserIdNonNegative: 'User id must be a non negative number',
    UserFirstnameShouldBeValid: 'First name must be between 2 and 50 characters and contain valid characters.',
    UserLastnameShouldBeValid: 'Last name must be between 2 and 50 characters and contain valid characters.',
    UserEmailShouldBeValid: 'Email must be a valid email address.',
    UserPasswordShouldBeValid: 'Password must be between 8 and 50 characters and contain valid characters.',
    UserEmailCannotExceedLimit: 'Email cannot exceed 254 characters.',
    UserInvalidHashPassword: 'Invalid hash password',
    UserInvalidSalt: 'Invalid salt',
    BookIdNonNegative: 'Book id must be a non negative number',
    BookTitleShouldBeValid: 'Title must be between 2 and 50 characters and contain valid characters.',
    BookDescriptionShouldBeValid: 'Description must be between 2 and 500 characters and contain valid characters.',
    BookAuthorShouldBeValid: 'Author must be between 2 and 50 characters and contain valid characters.',
    BookGenreShouldBeValid: 'Genre must be between 2 and 50 characters and contain valid characters.',
    BookDescriptionTooLong: 'Description cannot exceed 500 characters.',
    BookIsbnShouldBeValid: 'ISBN must be between 10 and 13 characters and contain valid characters.',
    BookPublisherShouldBeValid: 'Publisher must be between 2 and 50 characters and contain valid characters.',
    BookYearShouldBeValid: 'Year must be between 1900 and 2021.',
    BookImageUrlShouldBeValid: 'Image url must be a valid url.',
    BookRatingShouldBeValid: 'Rating must be between 0 and 5.',
    BookNumberOfRatingsReviewsShouldBeValid: 'Number of ratings and reviews must be between 0 and 5.',
    PublisherIdNonNegative: "Publisher id must be a non negative number",
    PublisherTitleShouldBeValid: "Publisher title must be between 2 and 50 characters and contain valid characters.",
    PublisherDescriptionNotDefined: "Publisher description not defined",
    PublisherCityNotDefined: "Publisher city not defined",
    PublisherStateNotDefined: "Publisher state not defined",
    PublisherZipCodeNotFound: "Publisher zip code not found",
    AuthorIdNonNegative: "Author id must be a non negative number",
}